defaults: &defaults
  docker:
  - image: circleci/openjdk:11-jdk-node-browsers
  working_directory: ~/repo
  environment:
    JVM_OPTS: -Xmx1024m
    TERM: dumb

gradle_caching: &gradle_caching
- restore_cache:
    keys:
    - v1-dependencies-{{ checksum "build.gradle" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-
- run: gradle dependencies
- save_cache:
    paths:
    - ~/.gradle
    key: v1-dependencies-{{ checksum "build.gradle" }}

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    <<: *gradle_caching
    - run: gradle clean test --info